[profile.default]
src = 'contracts/v2'
out = 'artifacts'
libs = ["node_modules", "lib"]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]
ignored_error_codes = [
    2018,
    2072,
    5574,
    5667,
    5740,
    6321,
    8261,
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config